name: Sentiment Analysis

on:
  schedule:
    - cron: '30 5 * * *'  # Runs every day at 07:00 UTC

jobs:
  analyze_sentiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Sentiment Analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  # Access the secret
        run: python sentiment_analysis.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add A2b January month.xlsx  # Only add modified file
          git commit -m "Automated sentiment analysis update" || echo "No changes to commit" # Avoid error if no changes
          git push origin main #or your main branch
