name: Sentiment Analysis

on:
  schedule:
    - cron: '30 9 * * *'  # Runs daily at 08:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze_sentiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Sentiment Analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python sentiment_analysis.py

      - name: Debug File Existence
        run: |
          ls -la
          cat A2b_January_month.xlsx || echo "File does not exist or is empty"

      - name: Ensure Git Detects Changes
        run: echo "Updated on $(date)" >> A2b_January_month.xlsx

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add "A2b_January_month.xlsx"
          git commit -m "Automated sentiment analysis update" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Yaswanth-Magil/Sentiment-Analysis-Dumy.git main
