name: Sentiment Analysis

on:
  schedule:
    - cron: '12 7 * * *'  # Runs every day at 11:40 AM IST

  workflow_dispatch: # Allows manual triggering

permissions: # Added the permissions block
  contents: write # Allows the workflow to modify the repository's contents
  pull-requests: write # Allows the workflow to create and manage pull requests (if needed)

jobs:
  analyze_sentiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Sentiment Analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  # Access the secret
        run: python sentiment_analysis.py

      - name: Set File Permissions # Added a step to explicitly change file permissions
        run: chmod +w A2B_January_month.xlsx # Grant write permissions

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add A2B_January_month.xlsx  # Corrected capitalization
          git commit -m "Automated sentiment analysis update" || echo "No changes to commit" # Avoid error if no changes
          git push origin main #or your main branch
